name: varied_rent
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^1.1.0
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.0
  equatable: ^1.1.0
  flutter_bloc: ^4.0.0
  flutter_custom_clippers: ^1.1.1
  after_layout: ^1.0.7+2
  fluttericon: ^1.0.7
  mask_text_input_formatter: ^1.0.6
  mask_shifter: ^0.1.0
  dio: 3.0.9
  flutter_keyboard_visibility: ^3.1.0
  bottom_navy_bar: ^5.4.0
  ff_navigation_bar: ^0.1.5
  persistent_bottom_nav_bar: ^1.5.5
  circular_bottom_navigation: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  http: any
  shared_preferences: any

flutter:

  uses-material-design: true
